// <auto-generated />
using AppPrawject.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppPrawject.Data.Migrations
{
    [DbContext(typeof(AppPrawjectDbContext))]
    [Migration("20190514131911_pet-seeding-and-relationship")]
    partial class petseedingandrelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppPrawject.Domain.Model.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Breed")
                        .IsRequired();

                    b.Property<string>("Image");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("PetBreedId");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("PetBreedId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("AppPrawject.Domain.Model.PetBreed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("PetBreeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Labrador"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Chihuahua"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Poodle"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Beagle"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Mixed Breed"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Boston Terrier"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Collie"
                        },
                        new
                        {
                            Id = 8,
                            Description = "French Bulldog"
                        },
                        new
                        {
                            Id = 9,
                            Description = "German Shepherd"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Pug"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Bulldog"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Siberian Husky"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Great Dane"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Rottweiler"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Yorkshire Terrier"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Golden Retriever"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Boxer"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Australian Shepherd"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Bichon Frise"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Chow Chow"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Pointer"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Dachshund"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Pomeranian"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Pembroke Welsh Corgi"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Bernese Mountain Dog"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Basset Hound"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Greyhound"
                        },
                        new
                        {
                            Id = 28,
                            Description = "American Staffordshire Terrier"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Jack Russell Terrier"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Australian Cattle Dog"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Alaskan Malamute"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Akita"
                        },
                        new
                        {
                            Id = 33,
                            Description = "American Foxhound"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Vizsla"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Scottish Terrier"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Weimaraner"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Doberman"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Bullterrier"
                        },
                        new
                        {
                            Id = 39,
                            Description = "English Mastiff"
                        },
                        new
                        {
                            Id = 40,
                            Description = "Pitbull"
                        });
                });

            modelBuilder.Entity("AppPrawject.Domain.Model.Pet", b =>
                {
                    b.HasOne("AppPrawject.Domain.Model.PetBreed", "PetBreed")
                        .WithMany()
                        .HasForeignKey("PetBreedId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
